Fix RT1176 USB interrupt name - use USB_OTG1_IRQn
Changed from USB1_IRQn to USB_OTG1_IRQn to match RT1176 device header.
The RT1176 defines USB interrupts as USB_OTG1_IRQn (136) and USB_OTG2_IRQn (135).

Fixes build error:
error: 'USB1_IRQn' undeclared (first use in this function)

File: board/usb_device_board_init.c line 52